import xarray as xr
from pathlib import Path
import numpy as np

def modify_jcm_terrain(
    reference_file: str,
    planet_type: str,
    output_directory: str = "./data",
):

    reference_file = Path(reference_file)
    output_directory = Path(output_directory)
    output_file = (output_directory / f"terrain_{planet_type:s}.nc").resolve()
    output_directory.mkdir(parents=True, exist_ok=True)
    
    print(f"Modifying reference jcm terrain file: {str(reference_file)}")
    print(f"Target output file: {str(output_file)}")
    
    ds = xr.open_dataset(reference_file)
    print("Loaded xarray metadata")
    print(ds)
    
    llon, llat = np.meshgrid(
        ds.coords["lon"].to_numpy() % 360,
        ds.coords["lat"].to_numpy(),
        indexing = "ij",
    )
    
    cap_edge_latitude = 75.0
    
    divider_width = 3.75
    basin1_lon_beg = 0.0
    basin1_lat_edge = -10.0
    
    basin2_lon_beg = 120.0
    basin2_lat_edge = -50.0
    
    cap_threshold_latitude = 75.0
    
    if planet_type == "capped_earth":
        mask = np.where(
            ( ds["lsm"].to_numpy() == 1 )
            | (np.abs(llat) >= cap_threshold_latitude)
            , 1
            , 0
        ).astype(int)
    elif planet_type == "aquaplanet":
        mask = np.where(
            np.abs(llat) >= cap_threshold_latitude
            , 1
            , 0
        ).astype(int)
    elif planet_type == "toy_earth":
         mask = np.where(
            (np.abs(llat) >= cap_threshold_latitude)
            | (
                (llat >= basin1_lat_edge)
                & (llon >= basin1_lon_beg)
                & (llon < basin1_lon_beg + divider_width)
            )
            | (
                (llat >= basin2_lat_edge)
                & (llon >= basin2_lon_beg)
                & (llon < basin2_lon_beg + divider_width)
            )
            , 1
            , 0
        ).astype(int)

    elif planet_type == "double_drake":

        # original setup    
        cap_edge_latitude = 75.0
        divider_width = 3.85
        basin1_lon_beg = 0.0
        basin1_lat_edge = -45.0
        
        basin2_lon_beg =   67.5
        basin2_lat_edge = -45.0
     
        mask = np.where(
            (np.abs(llat) >= cap_edge_latitude)
            | (
                (llat >= basin1_lat_edge)
                & (llon >= basin1_lon_beg)
                & (llon < basin1_lon_beg + divider_width)
            )
            | (
                (llat >= basin2_lat_edge)
                & (llon >= basin2_lon_beg)
                & (llon < basin2_lon_beg + divider_width)
            )
            , 1
            , 0
        ).astype(int)
 
    elif planet_type == "double_drake_equal_basin_width":

        # original setup    
        cap_edge_latitude = 75.0
        divider_width     =  3.85

        basin1_lon_beg    =   0.0
        basin1_lat_edge   = -45.0
        
        basin2_lon_beg    = 180.0
        basin2_lat_edge   = -45.0
     
        mask = np.where(
            (np.abs(llat) >= cap_edge_latitude)
            | (
                (llat >= basin1_lat_edge)
                & (llon >= basin1_lon_beg)
                & (llon < basin1_lon_beg + divider_width)
            )
            | (
                (llat >= basin2_lat_edge)
                & (llon >= basin2_lon_beg)
                & (llon < basin2_lon_beg + divider_width)
            )
            , 1
            , 0
        ).astype(int)
 
    else:
        raise Exception(f"Unknown `--planet-type`: {args.planet_type}") 
    
    ds["lsm"].data[:] = mask
    ds["orog"].data[:] = 0.0 

    print(f"Writing result to: {str(output_file)}")
    ds.to_netcdf(output_file)
    ds.close()
    return output_file



if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--reference-file", type=str, help="The reference terrain file generated by jcm.", required=True)
    parser.add_argument("--planet-type", type=str, help="The type of planet to generate.", choices=["capped_earth", "aquaplanet", "toy_earth"])
    parser.add_argument("--output-directory", type=str, help="Directory to output the file.", default=".")
    
    args = parser.parse_args()
    print(args)
    
    modify_jcm_terrain(args.reference_file, args.planet_type, args.output_directory)




