#!/usr/bin/env python

"""
This Veros setup file was generated by

   $ veros copy-setup acc

on 2026-02-02 08:22:24 UTC.
"""

__VEROS_VERSION__ = '1.6.1'

if __name__ == "__main__":
    raise RuntimeError(
        "Veros setups cannot be executed directly. "
        f"Try `veros run {__file__}` instead."
    )

# -- end of auto-generated header, original file below --

import veros
print(f"Veros path: {veros.__file__:s}")

from veros import VerosSetup, veros_routine
from veros.variables import allocate, Variable
from veros.distributed import global_min, global_max
from veros.core.operators import numpy as npx, update, at
from typing import Sequence

import jax.numpy as npx
import xarray as xr

def generateVerosSetup(
    land_sea_mask_file: str,
    ddz: Sequence[float] = [50.0, 70.0, 100.0, 140.0, 190.0, 240.0, 290.0, 340.0, 390.0, 440.0, 490.0, 540.0, 590.0, 640.0, 690.0],
    dt_mom: float = 1800.0,
    dt_tracer: float = 1800.0,
):

    mask_ds = xr.open_dataset(land_sea_mask_file)

    # `lat_bnds`/`lon_bnds` are the un-rotated (pre-rotation) bounds of the
    # regular j/i computational grid -- these size the Veros grid itself.
    lat_bnds = mask_ds["lat_bnds"].to_numpy()
    lon_bnds = mask_ds["lon_bnds"].to_numpy()
    ny, nx = lat_bnds.shape[0], lon_bnds.shape[0]
    dyt = float(lat_bnds[0, 1] - lat_bnds[0, 0])
    dxt = float(lon_bnds[0, 1] - lon_bnds[0, 0])
    y_origin: float = float(lat_bnds[0, 0])
    x_origin: float = float(lon_bnds[0, 0])

    # `true_lat` is the actual geographic latitude of each (j, i) cell.
    # Since the grid's poles are rotated away from the real poles, this is
    # not the same as the grid's own yt latitude, so it must be used for
    # the Coriolis parameter instead of yt.
    true_lat = mask_ds["true_lat"].to_numpy().transpose()  # (j, i) -> (xt, yt)

    def get_land_sea_mask():
        # file convention: 1 = land, 0 = sea; Veros kbot wants 0 = land
        return 1 - mask_ds["land_sea_mask"].to_numpy().astype(int).transpose()

    p = 1.4

    ddz = npx.array(ddz)
    nz = len(ddz)

    class VerosCaseSetup(VerosSetup):
        """A model using spherical coordinates with a partially closed domain.

        Wind forcing over the channel part and buoyancy relaxation drive a large-scale meridional overturning circulation.

        This setup demonstrates:
         - setting up an idealized geometry
         - updating surface forcings
         - basic usage of diagnostics

        `Adapted from pyOM2 <https://wiki.cen.uni-hamburg.de/ifm/TO/pyOM2/ACC%202>`_.
        """

        @veros_routine
        def set_parameter(self, state):
            settings = state.settings
            settings.identifier = "output_veros"
            settings.description = "My Veros setup"
        
            settings.enable_nan_checks = False

            settings.nx, settings.ny, settings.nz = nx, ny, nz
            settings.dt_mom = dt_mom
            settings.dt_tracer = dt_tracer
            settings.runlen = 86400 * 365

            settings.x_origin = x_origin
            settings.y_origin = y_origin

            settings.coord_degree = True
            settings.enable_cyclic_x = True

            settings.enable_neutral_diffusion = True # False # Test 2026/06/16: turn it off to see if model can integrate 1000 years
            settings.K_iso_0 = 1000.0
            settings.K_iso_steep = 500.0
            settings.iso_dslope = 0.005
            settings.iso_slopec = 0.01
            settings.enable_skew_diffusion = True

            settings.enable_hor_friction = True
            settings.A_h = ( (dxt+dyt)/2 * settings.degtom) ** 3 * 2e-11
            settings.enable_hor_friction_cos_scaling = True
            settings.hor_friction_cosPower = 1

            settings.enable_bottom_friction = True
            settings.r_bot = 1e-5
            
            #settings.enable_biharmonic_friction = True
            #settings.A_hbi = 1e16

            settings.enable_implicit_vert_friction = True

            settings.enable_tke = True
            settings.c_k = 0.1
            settings.c_eps = 0.7
            settings.alpha_tke = 30.0
            settings.mxl_min = 1e-8
            settings.tke_mxl_choice = 2
            settings.kappaM_min = 2e-4
            settings.kappaH_min = 2e-5
            settings.enable_kappaH_profile = True

            settings.K_gm_0 = 1000.0
            settings.enable_eke = True
            settings.eke_k_max = 1e4
            settings.eke_c_k = 0.4
            settings.eke_c_eps = 0.5
            settings.eke_cross = 2.0
            settings.eke_crhin = 1.0
            settings.eke_lmin = 100.0
            settings.enable_eke_superbee_advection = True
            settings.enable_eke_isopycnal_diffusion = True

            settings.enable_idemix = False

            settings.eq_of_state_type = 1

            var_meta = state.var_meta
            var_meta.update(
                t_star=Variable("t_star", ("yt",), "deg C", "Reference surface temperature"),
                t_rest=Variable("t_rest", ("xt", "yt"), "1/s", "Surface temperature restoring time scale"),
            )

        @veros_routine
        def set_grid(self, state):
            vs = state.variables
            #ddz = npx.array(
            #    [50.0, 70.0, 100.0, 140.0, 190.0, 240.0, 290.0, 340.0, 390.0, 440.0, 490.0, 540.0, 590.0, 640.0, 690.0]
            #)
            vs.dxt = update(vs.dxt, at[...], dxt)
            vs.dyt = update(vs.dyt, at[...], dyt)
            vs.dzt = update(vs.dzt, at[...], ddz[::-1]) # ocean grid starts from below


        @veros_routine
        def set_coriolis(self, state):
            vs = state.variables
            settings = state.settings
            vs.coriolis_t = update(
                vs.coriolis_t, at[2:-2, 2:-2], 2 * settings.omega * npx.sin(true_lat / 180.0 * settings.pi)
            )

        @veros_routine
        def set_topography(self, state):
            vs = state.variables
            x, y = npx.meshgrid(vs.xt, vs.yt, indexing="ij")
             
            vs.kbot = npx.zeros_like(x)
            vs.kbot = update(
                vs.kbot,
                at[2:-2, 2:-2],
                get_land_sea_mask()
            )


        @veros_routine
        def set_initial_conditions(self, state):
            vs = state.variables
            settings = state.settings

            # initial conditions
            y_center = 10.0
            sigma = 15.0
            amplitude = 5.0
            distace_square = ((vs.yt[None, :, None] - y_center) ** 2) / (2 * sigma ** 2)
            temp_anomaly = 5.0 * npx.exp(-distace_square) * vs.maskT * 0
           
            vs.temp = update(vs.temp, at[...], ((1 - vs.zt[None, None, :] / vs.zw[0]) * 15 * vs.maskT + temp_anomaly)[..., None] )
            vs.salt = update(vs.salt, at[...], 35.0 * vs.maskT[..., None])

            # wind stress forcing
            yt_min = global_min(vs.yt.min())
            yu_min = global_min(vs.yu.min())
            yt_max = global_max(vs.yt.max())
            yu_max = global_max(vs.yu.max())

            taux = allocate(state.dimensions, ("yt",))
            taux = npx.where(vs.yt < -20, 0.1 * npx.sin(settings.pi * (vs.yu - yu_min) / (-20.0 - yt_min)), taux)
            taux = npx.where(vs.yt > 10, 0.1 * (1 - npx.cos(2 * settings.pi * (vs.yu - 10.0) / (yu_max - 10.0))), taux)
            vs.surface_taux = taux * vs.maskU[:, :, -1]

            # surface heatflux forcing
            vs.t_star = allocate(state.dimensions, ("yt",), fill=15)
            vs.t_star = npx.where(vs.yt < -20, 15 * (vs.yt - yt_min) / (-20 - yt_min), vs.t_star)
            vs.t_star = npx.where(vs.yt > 20, 15 * (1 - (vs.yt - 20) / (yt_max - 20)), vs.t_star)
            vs.t_rest = vs.dzt[npx.newaxis, -1] / (30.0 * 86400.0) * vs.maskT[:, :, -1]

            if settings.enable_tke:
                vs.forc_tke_surface = update(
                    vs.forc_tke_surface,
                    at[2:-2, 2:-2],
                    npx.sqrt(
                        (0.5 * (vs.surface_taux[2:-2, 2:-2] + vs.surface_taux[1:-3, 2:-2]) / settings.rho_0) ** 2
                        + (0.5 * (vs.surface_tauy[2:-2, 2:-2] + vs.surface_tauy[2:-2, 1:-3]) / settings.rho_0) ** 2
                    )
                    ** (1.5),
                )

            if settings.enable_idemix:
                vs.forc_iw_bottom = 1e-6 * vs.maskW[:, :, -1]
                vs.forc_iw_surface = 1e-7 * vs.maskW[:, :, -1]

        @veros_routine
        def set_forcing(self, state):
            pass
            #vs = state.variables
            #vs.forc_temp_surface = vs.t_rest * (vs.t_star - vs.temp[:, :, -1, vs.tau])

        @veros_routine
        def set_diagnostics(self, state):
            settings = state.settings
            diagnostics = state.diagnostics
            diagnostics.clear()       
            
            """
            diagnostics["snapshot"].output_frequency = 86400 * 10
            diagnostics["averages"].output_variables = (
                "salt",
                "temp",
                "u",
                "v",
                "w",
                "psi",
                "surface_taux",
                "surface_tauy",
            )
            diagnostics["averages"].output_frequency = 365 * 86400.0
            diagnostics["averages"].sampling_frequency = settings.dt_tracer * 10
            diagnostics["overturning"].output_frequency = 365 * 86400.0 / 48.0
            diagnostics["overturning"].sampling_frequency = settings.dt_tracer * 10
            diagnostics["tracer_monitor"].output_frequency = 365 * 86400.0 / 12.0
            diagnostics["energy"].output_frequency = 365 * 86400.0 / 48
            diagnostics["energy"].sampling_frequency = settings.dt_tracer * 10
            """
        @veros_routine
        def after_timestep(self, state):
            pass

    return VerosCaseSetup
